// Words that can be formed from home row keys
const HOME_ROW_WORDS = [
    'ad', 'ah', 'as', 'al', 'la', 'ha', 'sh',
    'add', 'ads', 'age', 'ash', 'ask', 'dad',
    'fad', 'gag', 'gal', 'gas', 'had', 'hag',
    'has', 'jag', 'lag', 'lad', 'lass', 'saga',
    'glad', 'half', 'hall', 'hash', 'lash', 'lass',
    'salad', 'shall', 'flash', 'slash', 'glass',
    'fall', 'all', 'shall', 'flask', 'dash', 'dads',
    'sad', 'sag', 'lag', 'jag', 'gag', 'dal',
];

export const LEVELS = [
    {
        id: 1,
        name: "Home Base",
        description: "The two home keys",
        keys: ['f', 'j'],
        tileSpeed: 45,
        spawnInterval: 1.6,
        maxActiveTiles: 6,
        minWordLength: 1,
        maxWordLength: 1,
        totalTiles: 20,
        wordList: []
    },
    {
        id: 2,
        name: "Neighbors",
        description: "Middle fingers join in",
        keys: ['f', 'j', 'd', 'k'],
        tileSpeed: 48,
        spawnInterval: 1.5,
        maxActiveTiles: 7,
        minWordLength: 1,
        maxWordLength: 1,
        totalTiles: 24,
        wordList: []
    },
    {
        id: 3,
        name: "Reaching Out",
        description: "Ring fingers",
        keys: ['f', 'j', 'd', 'k', 's', 'l'],
        tileSpeed: 50,
        spawnInterval: 1.4,
        maxActiveTiles: 7,
        minWordLength: 1,
        maxWordLength: 1,
        totalTiles: 26,
        wordList: []
    },
    {
        id: 4,
        name: "Full Home Row",
        description: "All home row keys",
        keys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';'],
        tileSpeed: 50,
        spawnInterval: 1.3,
        maxActiveTiles: 8,
        minWordLength: 1,
        maxWordLength: 1,
        totalTiles: 28,
        wordList: []
    },
    {
        id: 5,
        name: "Index Stretch",
        description: "G and H keys",
        keys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';', 'g', 'h'],
        tileSpeed: 52,
        spawnInterval: 1.2,
        maxActiveTiles: 8,
        minWordLength: 1,
        maxWordLength: 1,
        totalTiles: 30,
        wordList: []
    },
    {
        id: 6,
        name: "Word Builder",
        description: "Home row combos",
        keys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';', 'g', 'h'],
        tileSpeed: 42,
        spawnInterval: 1.8,
        maxActiveTiles: 6,
        minWordLength: 2,
        maxWordLength: 2,
        totalTiles: 22,
        wordList: HOME_ROW_WORDS.filter(w => w.length === 2)
    },
    {
        id: 7,
        name: "Top Row Start",
        description: "R and U keys",
        keys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';', 'g', 'h', 'r', 'u'],
        tileSpeed: 48,
        spawnInterval: 1.5,
        maxActiveTiles: 7,
        minWordLength: 1,
        maxWordLength: 2,
        totalTiles: 26,
        wordList: HOME_ROW_WORDS.filter(w => w.length <= 2)
    },
    {
        id: 8,
        name: "Expanding Reach",
        description: "E and I keys",
        keys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';', 'g', 'h', 'r', 'u', 'e', 'i'],
        tileSpeed: 50,
        spawnInterval: 1.4,
        maxActiveTiles: 8,
        minWordLength: 1,
        maxWordLength: 2,
        totalTiles: 28,
        wordList: HOME_ROW_WORDS.filter(w => w.length <= 2)
    },
    {
        id: 9,
        name: "Wider Reach",
        description: "W and O keys",
        keys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';', 'g', 'h', 'r', 'u', 'e', 'i', 'w', 'o'],
        tileSpeed: 52,
        spawnInterval: 1.3,
        maxActiveTiles: 8,
        minWordLength: 2,
        maxWordLength: 2,
        totalTiles: 26,
        wordList: HOME_ROW_WORDS.filter(w => w.length === 2)
    },
    {
        id: 10,
        name: "Pinky Reach",
        description: "Q and P keys",
        keys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';', 'g', 'h', 'r', 'u', 'e', 'i', 'w', 'o', 'q', 'p'],
        tileSpeed: 54,
        spawnInterval: 1.2,
        maxActiveTiles: 8,
        minWordLength: 2,
        maxWordLength: 2,
        totalTiles: 28,
        wordList: HOME_ROW_WORDS.filter(w => w.length === 2)
    },
    {
        id: 11,
        name: "Top Complete",
        description: "T and Y keys",
        keys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';', 'g', 'h', 'r', 'u', 'e', 'i', 'w', 'o', 'q', 'p', 't', 'y'],
        tileSpeed: 52,
        spawnInterval: 1.4,
        maxActiveTiles: 8,
        minWordLength: 2,
        maxWordLength: 3,
        totalTiles: 28,
        wordList: HOME_ROW_WORDS.filter(w => w.length <= 3)
    },
    {
        id: 12,
        name: "Bottom Row Begins",
        description: "V and N keys",
        keys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';', 'g', 'h', 'r', 'u', 'e', 'i', 'w', 'o', 'q', 'p', 't', 'y', 'v', 'n'],
        tileSpeed: 54,
        spawnInterval: 1.3,
        maxActiveTiles: 8,
        minWordLength: 2,
        maxWordLength: 3,
        totalTiles: 30,
        wordList: HOME_ROW_WORDS.filter(w => w.length <= 3)
    }
];
